apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 2
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: exgon21c/kubia
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
